apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-static-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webolith
        component: nginx
    spec:
      containers:
        - name: nginx
          image: domino14/webolith-nginx
          readinessProbe:
            exec:
              command:
              - cat
              - /usr/share/nginx/html/50x.html
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 3
            initialDelaySeconds: 3

          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "rm /usr/share/nginx/html/50x.html && sleep 15 && /usr/sbin/nginx -s quit"]
